apiVersion: apps/v1
kind: Deployment
metadata:
  name: spt-fe
spec:
  template:
    spec:
      containers:
        - name: spt-fe
          imagePullPolicy: IfNotPresent
---

apiVersion: v1
kind: Service
metadata:
  name: spt-fe
spec:
  type: LoadBalancer
