apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-update
spec:
  schedule: "0 * * * *" #	Run every hour
  startingDeadlineSeconds: 1800 # 30 min
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: spt-update-data
              image: spt-backend-image
              imagePullPolicy: IfNotPresent
              command:
                - poetry
                - run
                - spot_price_tracker
                - update-data
                - --start-days-ago
                - "1"
                - -t
                - "30"
              env:
                - name: DATABASE_URL
                  value: "timescaledb://postgres@timescaledb-sts-0.timescaledb.spot-price-tracker.svc.cluster.local:5432/spotpricetracker" # FIXME
          restartPolicy: Never