---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-database-url
  namespace: spot-price-tracker
spec:
  encryptedData:
    backend-database-url: AgC5fC6cAFZ0FZdSVAE7R27RsFe7Zi9rr/H9+FZh1IG54Bx4gnMZRYTn/p2aBLNg7AGDT/OJA0NhAQb5Xm5tYwGQOT3e3W2qhcDc6a7DbmuLdFTjoCnNrcGYjuQXYVzDJag8u8eDYOhs1Xd5D9ycWGsAk65IH7qtZlAoUOkyV+4a22C+4J1fDF4Q2gchO9kVZwnKpPp2TRI/CRT++j3S+IvVtK8FrcLe7LNPRpSFhuoCuJkCxdN8XGKOgyWLR2tPO5cVj4itKwhLzNypjrtqB3r34SQGNjwM4JnL3762O54eQvT14eEavDuuDa70/rbbeQZJqJkttxFx0glEuI4OpWxrBQZ0J+00v0Yg1Ku7M1XTBdbIymtjusyrEDXe6QwlYUiEFYBPNZARZvD6ZBNY6bNxSMy56aeKdsd0GLtTUFwLS7MkqnbXyZYUPq9rxka/1S7JvoLH/FmIZ3XwD+iTsb9EqO5OwKqC+UM5TdDxTraLt6xUesWDVuC1igk1q5McMJeaqIaRP1eKVRl1YpBCyQLHkOOQVEOkBSLHOn3cgLtyAO6b2de9hLek9XXfjE7x20rPYsvrkWD0a+z70tuPlZpOESuOq+lAlTNx3984XfqUk8IptzjvVNGfjSUPHAyhGuXZf94j1Rp+gD1Q0XSc6o5/3yxd/yXZ/9tEVs8pR/WnDqT0voMvzAVSZsA4XG5h+MGfe58/93eZ6U/RSzFU6QXJL4P1yN75t59M/H4V2XhEsRzmSBTh7AldoHPuL832E7cVKpCPltyh0hGbjA0i1spQVX1bBgl6cuSyBFgwh/XmbaHVs5o4ns/pZMl828HQSkMU36ZmDv1kl2AoUUZznMVXQHCZAm6cN8NpgAOn61THWh1MprSGL+dy2A==
  template:
    metadata:
      creationTimestamp: null
      name: backend-database-url
      namespace: spot-price-tracker
