apiVersion: apps/v1
kind: Deployment
metadata:
  name: spt-fe
spec:
  template:
    spec:
      containers:
        - name: spt-fe
          env:
            - name: PUBLIC_API_URL
              value: https://api.spotpricetracker.com
            - name: PRIVATE_API_URL
              value: http://spt-backend.spot-price-tracker.svc.cluster.local
