apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spot-price-tracker
resources:
- ../../base
- db-admin-sealed-secret.yaml
- timescaledb.yaml
- backend-database-url-sealed-secret.yaml
- data_update_cron.yaml
- ing.yaml
patches:
- path: backend_deployment.yaml
- path: fe_deployment.yaml
images:
- name: spt-backend-image
  newName: "6960041"
- name: spt-frontend-image
  newName: e3e0816
