"""Add cores column to instance_types

Revision ID: c96821e519c3
Revises: d5856c32131f
Create Date: 2024-12-15 13:16:23.958244

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c96821e519c3"
down_revision: Union[str, None] = "d5856c32131f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "instance_types",
        sa.Column("cores", sa.Integer(), nullable=False, server_default="0"),
    )
    op.execute("UPDATE instance_types SET cores = v_cores / 2")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instance_types", "cores")
    # ### end Alembic commands ###
