"""initial migration

Revision ID: d5856c32131f
Revises:
Create Date: 2024-12-14 16:30:20.840688

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5856c32131f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "instance_types",
        sa.Column("instance_type", sa.String(), nullable=False),
        sa.Column("v_cores", sa.Integer(), nullable=False),
        sa.Column("sustained_clock_speed_ghz", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("instance_type"),
    )
    op.create_table(
        "spot_instance_prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("instance_type", sa.String(), nullable=False),
        sa.Column("product_description", sa.String(), nullable=True),
        sa.Column("price_usd_hourly", sa.Float(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("availability_zone", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instance_type"],
            ["instance_types.instance_type"],
            name="fk_spot_instance_prices_instance_type",
        ),
        sa.PrimaryKeyConstraint("id", "timestamp", name="pk_spot_instance_prices"),
    )
    op.create_index(
        op.f("ix_spot_instance_prices_availability_zone"),
        "spot_instance_prices",
        ["availability_zone", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spot_instance_prices_instance_type"),
        "spot_instance_prices",
        ["instance_type", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spot_instance_prices_region"),
        "spot_instance_prices",
        ["region", "timestamp"],
        unique=False,
    )
    op.execute(
        "SELECT create_hypertable('spot_instance_prices', by_range('timestamp', INTERVAL '24 hours'))"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_spot_instance_prices_timestamp"), table_name="spot_instance_prices"
    )
    op.drop_index(
        op.f("ix_spot_instance_prices_region"), table_name="spot_instance_prices"
    )
    op.drop_index(
        op.f("ix_spot_instance_prices_instance_type"), table_name="spot_instance_prices"
    )
    op.drop_index(
        op.f("ix_spot_instance_prices_product_description"),
        table_name="spot_instance_prices",
    )
    op.drop_index(
        op.f("ix_spot_instance_prices_availability_zone"),
        table_name="spot_instance_prices",
    )
    op.drop_table("spot_instance_prices")
    op.drop_table("instance_types")
    # ### end Alembic commands ###
